# Generated by Django 3.2.9 on 2022-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_data',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
